#spring:
#jpa:
#database-platform: org.hibernate.dialect.MySQLDialect
##    hibernate:
##      ddl-auto: update
##      dialect: org.hibernate.dialect.MySQL
##      database-platform: org.hibernate.dialect.MySQL
##    properties:
##      hibernate:
##        format_sql: true
##    show-sql: true
#datasource:
#username: root
#password:
#url: jdbc:mysql://localhost:3306/prometheus-demo?useSSL=false
#driverClassName: com.mysql.jdbc.Driver
